POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "+9111111111"
}

###
POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "+91111111111",
    "otp": 1879,
    "hash": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

